Some weights of ViTModel were not initialized from the model checkpoint at google/vit-base-patch16-224 and are newly initialized: ['pooler.dense.bias', 'pooler.dense.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "d:\Internship_Tasks\Maharshi_Animal-_and_Human_Detection_Model\dst\mmm.py", line 124, in <module>
    loss.backward()
  File "C:\Users\dhaba\anaconda3\envs\MH\Lib\site-packages\torch\_tensor.py", line 648, in backward
    torch.autograd.backward(
  File "C:\Users\dhaba\anaconda3\envs\MH\Lib\site-packages\torch\autograd\__init__.py", line 353, in backward
    _engine_run_backward(
  File "C:\Users\dhaba\anaconda3\envs\MH\Lib\site-packages\torch\autograd\graph.py", line 824, in _engine_run_backward
    return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt
Exception ignored in atexit callback: <function _start_and_connect_service.<locals>.teardown_atexit at 0x000001CD5F363EC0>
Traceback (most recent call last):
  File "C:\Users\dhaba\anaconda3\envs\MH\Lib\site-packages\wandb\sdk\lib\service_connection.py", line 90, in teardown_atexit
    conn.teardown(hooks.exit_code)
  File "C:\Users\dhaba\anaconda3\envs\MH\Lib\site-packages\wandb\sdk\lib\service_connection.py", line 218, in teardown
    self._router.join()
  File "C:\Users\dhaba\anaconda3\envs\MH\Lib\site-packages\wandb\sdk\interface\router.py", line 75, in join
    self._thread.join()
  File "C:\Users\dhaba\anaconda3\envs\MH\Lib\threading.py", line 1119, in join
    self._wait_for_tstate_lock()
  File "C:\Users\dhaba\anaconda3\envs\MH\Lib\threading.py", line 1139, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyboardInterrupt:
[0m
